"use client";

import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
  Legend,
} from "recharts";

const COLORS = [
  "#f97316",
  "#3b82f6",
  "#10b981",
  "#a855f7",
  "#ef4444",
  "#eab308",
  "#06b6d4",
];

export default function AdminCharts({ monthlySales, genreData }) {
  return (
    <div className="grid grid-cols-1 gap-6 xl:grid-cols-2">
      {/* Monthly Sales */}
      <div className="group overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-xl">
        <div className="border-b border-slate-100 bg-gradient-to-r from-orange-50 to-white px-6 py-5">
          <h3 className="text-lg font-semibold text-slate-900">
            Monthly Sales
          </h3>

          <p className="mt-1 text-sm text-slate-500">
            Revenue generated by month
          </p>
        </div>

        <div className="p-4 md:p-6">
          {monthlySales.length === 0 ? (
            <div className="flex h-[250px] items-center justify-center">
              <p className="text-sm text-slate-400">No sales data available</p>
            </div>
          ) : (
            <ResponsiveContainer width="100%" height={320}>
              <BarChart data={monthlySales}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />

                <XAxis dataKey="month" tick={{ fontSize: 12 }} />

                <YAxis tick={{ fontSize: 12 }} />

                <Tooltip />

                <Bar dataKey="revenue" fill="#f97316" radius={[8, 8, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          )}
        </div>
      </div>

      {/* Genre Distribution */}
      <div className="group overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-xl">
        <div className="border-b border-slate-100 bg-gradient-to-r from-blue-50 to-white px-6 py-5">
          <h3 className="text-lg font-semibold text-slate-900">
            Ebooks by Genre
          </h3>

          <p className="mt-1 text-sm text-slate-500">
            Genre distribution overview
          </p>
        </div>

        <div className="p-4 md:p-6">
          {genreData.length === 0 ? (
            <div className="flex h-[250px] items-center justify-center">
              <p className="text-sm text-slate-400">No genre data available</p>
            </div>
          ) : (
            <ResponsiveContainer width="100%" height={320}>
              <PieChart>
                <Pie
                  data={genreData}
                  dataKey="count"
                  nameKey="genre"
                  cx="50%"
                  cy="50%"
                  outerRadius={95}
                  label
                >
                  {genreData.map((_, index) => (
                    <Cell key={index} fill={COLORS[index % COLORS.length]} />
                  ))}
                </Pie>

                <Tooltip />
                <Legend />
              </PieChart>
            </ResponsiveContainer>
          )}
        </div>
      </div>
    </div>
  );
}
